In [46]:
#----------資料讀入並進行篩選----------
import pandas as pd

# 讀檔
TechnologyEquityETF= pd.read_csv('Technology Equity ETF List (75).csv') 
# 根據Inception欄位進行篩選
fliter = (TechnologyEquityETF["Inception"] < '2015-12-31') 
newTechnologyEquityETF = TechnologyEquityETF[fliter] 

#將符合的ETF代碼轉換為List
TechnologyEquityETFList = newTechnologyEquityETF['Symbol'].values.tolist()
 
print(TechnologyEquityETFList)

['QQQ', 'XLK', 'VGT', 'FDN', 'IYW', 'IXN', 'XT', 'IGV', 'QTEC', 'FTEC', 'FXL', 'KWEB', 'SKYY', 'HACK', 'RYT', 'IGM', 'ARKK', 'ROBO', 'SOXX', 'SMH', 'TDIV', 'CIBR', 'SOXL', 'PNQI', 'TECL', 'CQQQ', 'ARKW', 'XNTK', 'IPAY', 'EMQQ', 'PSCT', 'PSJ', 'ROM', 'XSD', 'PSI', 'IEUS', 'SOCL', 'XSW', 'PTF', 'SOXS', 'JHMT', 'ITEQ', 'PXQ', 'ISRA', 'IGN', 'USD', 'TECS', 'SSG', 'SCID', 'REW']

In [47]:
#設置日期範圍
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
import calendar
start_date = "2015-12-31"
stop_date = "2018-12-31"
start = datetime.strptime(start_date, "%Y-%m-%d")
stop = datetime.strptime(stop_date, "%Y-%m-%d")
print(start)
print(stop)

2015-12-31 00:00:00
2018-12-31 00:00:00

In [48]:
import requests
from bs4 import BeautifulSoup as bs

In [49]:
import datetime
def process_document(document, Symbol, start, stop):
    nodes = document.select('body > p')
    content = nodes[0].get_text().split( )
    arrayDate = content[0].split(',')
    arrayNAV = content[1].split(',')
    data = {'Date':arrayDate , Symbol: arrayNAV}
    df = pd.DataFrame.from_dict(data)
    nwedf = pd.DataFrame()
    while start <= stop:
        start = datetime.datetime.combine(start, datetime.time())
        _, last_day_num = calendar.monthrange(start.year, start.month)
        last_day = datetime.date(start.year, start.month, last_day_num) #獲得當月最後一天
        nwedf = pd.concat([nwedf, df[df["Date"] <= last_day.strftime('%Y%m%d')].iloc[-1:]], axis=0, ignore_index=True)
        start = start + relativedelta(months=1) #每次增加一個月
    nwedf.set_index("Date" , inplace=True)    
    return nwedf

In [50]:
all_data = pd.DataFrame()
for Symbol in TechnologyEquityETFList:
    print('start crawling :', Symbol)
    res = requests.get('https://www.moneydj.com/etf/x/Basic/ETF/X/xdjbcd/Basic0003BCD.xdjbcd?etfid='+Symbol+'&b='+start_date+'&c='+stop_date)
    doc = bs(res.text, 'lxml')
    if len(doc):
        data = process_document(doc, Symbol,start,stop)
        all_data = pd.concat([all_data, data], axis=1)
    else:
        print("已下檔")

start crawling : QQQ
start crawling : XLK
start crawling : VGT
start crawling : FDN
start crawling : IYW
start crawling : IXN
start crawling : XT
start crawling : IGV
start crawling : QTEC
start crawling : FTEC
start crawling : FXL
start crawling : KWEB

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

start crawling : SKYY
start crawling : HACK
start crawling : RYT
start crawling : IGM
start crawling : ARKK
start crawling : ROBO
start crawling : SOXX
start crawling : SMH
start crawling : TDIV
start crawling : CIBR
start crawling : SOXL
start crawling : PNQI
start crawling : TECL
start crawling : CQQQ
start crawling : ARKW
start crawling : XNTK
start crawling : IPAY
start crawling : EMQQ
start crawling : PSCT
start crawling : PSJ
start crawling : ROM
start crawling : XSD
start crawling : PSI
start crawling : IEUS
start crawling : SOCL
start crawling : XSW
start crawling : PTF
start crawling : SOXS
start crawling : JHMT
start crawling : ITEQ
start crawling : PXQ
start crawling : ISRA
start crawling : IGN
start crawling : USD
start crawling : TECS
start crawling : SSG
start crawling : SCID
start crawling : REW

In [51]:
#呈現COMMODITY ETFs 月底基金淨值的表格
all_data

,QQQ,XLK,VGT,FDN,IYW,IXN,XT,IGV,QTEC,FTEC,...,JHMT,ITEQ,PXQ,ISRA,IGN,USD,TECS,SSG,SCID,REW
Date,,,,,,,,,,,,,,,,,,,,,
20151231,111.8700,42.8590,108.2700,74.6300,107.0200,97.8500,24.9000,103.7000,42.6400,32.8095,...,NaN,NaN,34.4600,28.8000,36.8500,14.3617,155.4500,83.1200,23.5100,45.9200
20160129,104.2600,41.3150,102.0600,66.2000,101.0600,92.5900,22.8100,95.0300,39.4200,30.9366,...,NaN,21.4700,30.5500,26.8900,32.8600,12.0700,167.0000,95.2000,22.0000,50.3700
20160229,102.5700,41.0057,101.0100,65.3800,99.7700,91.6100,22.7600,92.9800,39.8300,30.6261,...,NaN,22.2100,31.6800,26.5900,35.0700,11.8350,167.4000,94.5800,21.7300,50.9800
20160331,109.1700,44.3624,109.5200,68.2400,108.4900,100.0300,24.1800,100.6600,42.9300,33.2064,...,NaN,23.8900,33.8900,27.9400,36.5700,13.7783,128.6500,80.0800,23.2700,42.4600
20160429,105.7500,42.1457,104.3900,69.4600,102.3000,95.4500,24.2800,100.4000,40.9100,31.6545,...,NaN,23.6300,33.6500,27.2700,35.5800,12.5517,148.8000,86.8400,23.5200,47.5000
20160531,110.4300,44.2249,110.0600,73.1500,108.1800,99.8200,24.9100,106.2000,43.9600,33.3698,...,NaN,23.9400,34.0400,27.1600,35.8900,14.6367,127.6000,73.4800,23.5600,42.2200
20160630,107.5800,43.3810,107.0300,72.1100,105.2200,97.3000,24.3600,105.1500,43.3900,32.4425,...,NaN,23.8000,33.2400,26.6600,34.9700,14.6483,130.6000,71.4000,22.0700,43.8000
20160729,115.2200,46.4346,115.2600,77.5100,114.1300,105.3500,25.9500,110.2400,46.6700,34.9306,...,NaN,25.1800,36.9100,27.9000,37.1500,17.7000,105.8000,58.3200,23.1300,37.0600
20160831,116.4400,47.0082,117.8200,79.0900,116.5700,107.6900,25.9700,112.5500,49.1900,35.7098,...,29.8400,25.6100,38.1500,28.2300,39.0600,19.1800,101.7000,53.4800,23.2700,35.4400
20160930,118.7200,47.7808,120.3900,81.5800,119.0200,110.3700,26.3600,113.5600,50.8900,36.5093,...,30.5300,25.5800,40.1000,27.9300,40.9600,20.5850,94.5000,49.0600,23.6000,33.5800
20161031,116.9400,47.4327,119.7100,81.3600,118.5900,109.7700,25.2500,112.4300,50.9100,36.2973,...,30.1100,24.3500,38.5400,26.8000,40.1900,19.5467,96.3000,51.2400,22.6300,33.7200
20161130,117.4300,47.4781,120.2600,79.9200,118.9300,108.9800,26.2600,111.8200,52.1700,36.4662,...,30.7400,24.9600,40.5500,27.2900,43.0900,21.5850,94.8500,45.8000,21.9900,33.3200
20161230,118.3900,48.3036,121.4400,79.7900,120.2000,110.0400,26.7600,108.8100,52.6200,36.8348,...,30.7300,24.8800,40.3900,26.8400,43.6300,22.5767,88.0500,42.8000,22.1600,32.2500
20170131,124.5800,50.0967,126.7700,85.3200,125.9200,115.2700,27.9000,117.2000,56.3000,38.4488,...,32.1400,26.1100,41.3800,27.5500,44.2000,23.4200,78.7000,40.8800,22.7200,29.3100
20170228,130.0000,52.3685,133.0000,86.2000,132.1700,120.3500,29.0800,122.7800,58.5700,40.3389,...,33.6100,26.7600,42.3600,28.5800,46.1200,24.4500,68.8000,38.9400,23.0600,26.5600
20170331,132.3600,53.3112,135.5500,88.0500,135.1100,124.0700,29.7000,126.4500,60.1100,41.1206,...,34.3700,28.4000,43.9100,29.0200,45.5400,26.1033,64.2500,36.2000,24.0100,25.2100
20170428,135.9800,54.3703,138.7900,92.2100,138.1800,127.5300,30.4200,130.6400,61.2400,42.0974,...,35.1000,29.0300,43.5800,29.6400,44.9900,25.6300,60.5000,36.6000,25.2800,24.0700
20170531,141.2300,56.4932,144.9100,94.6800,144.1500,133.6000,31.7000,138.5100,64.9400,43.9614,...,36.5600,29.9800,44.5200,30.3700,45.2500,30.0033,53.5500,30.8400,26.5800,22.0200
20170630,137.4500,54.7372,140.8600,94.7300,139.7200,130.8500,31.6500,136.8700,62.4200,42.7344,...,35.4800,29.5200,43.5700,30.7700,45.7800,26.6667,57.6000,33.9800,26.3400,23.1500
20170731,143.1600,57.1706,146.6300,98.8600,144.8000,136.7200,32.7400,142.1500,64.2600,44.4950,...,36.6200,29.8100,44.1300,30.6300,46.3800,29.1733,50.4000,30.7600,27.3500,21.5000
20170831,146.0400,58.8235,151.1900,100.5000,149.7500,140.4500,33.5300,147.4500,65.9800,45.8783,...,37.6200,30.1600,44.5300,28.6300,45.5500,30.3767,45.9500,29.1600,27.4100,19.9800
20170929,145.5200,59.1256,152.0700,102.3500,149.9300,142.1900,34.2700,146.2500,68.1400,46.1552,...,38.3800,31.3800,45.5000,29.8000,46.1400,33.8300,44.6000,25.9000,28.2200,19.7900
20171031,152.1200,62.9572,163.2500,107.4600,161.5400,152.7800,34.9100,156.4100,72.8200,49.5456,...,40.9400,32.4400,45.9500,29.7600,46.4200,41.3000,36.8000,21.0600,28.4300,16.9900
20171130,155.2300,63.8644,165.1300,108.9700,163.1000,154.1700,35.4000,155.8300,72.5300,50.1166,...,41.2700,32.0900,47.1400,30.0100,48.8800,41.7533,35.1000,20.5400,28.6200,16.6100
20171229,155.6800,63.8862,164.6400,109.8100,162.6700,153.3800,35.4100,154.5200,71.9200,49.9592,...,41.0400,31.6100,46.0900,30.3700,48.1300,40.6833,34.6000,20.8600,27.8300,16.6100
20180131,169.1800,68.4114,177.0400,121.7900,174.3500,164.7100,37.8600,170.0900,77.5300,53.7238,...,44.2100,33.0400,48.5100,31.6900,50.3500,46.6800,28.0000,17.8000,29.3500,14.4000
20180228,167.1000,68.1589,177.3000,123.0800,175.1200,163.2600,36.8700,171.5000,77.3400,53.7851,...,44.3900,32.7300,49.4700,30.4400,51.2900,46.9000,27.1500,16.9800,27.9000,13.9700
20180329,160.2300,65.4435,171.0500,120.5500,168.2500,157.6700,36.2600,169.7000,76.1200,51.8859,...,43.3000,31.9900,49.3900,29.8200,51.4800,44.8333,29.4800,17.1200,27.6700,14.8000
20180430,160.8600,65.4453,170.8700,123.7800,167.9700,157.7100,36.0100,173.6300,74.7300,51.8374,...,42.8700,32.3800,50.0800,29.8500,51.6500,40.0667,28.9300,18.5200,28.2900,14.6900
20180531,169.9500,69.8064,182.9100,134.3200,180.5100,166.6600,36.6500,182.9300,78.7000,55.5371,...,45.5100,34.3100,52.3500,31.4000,51.1800,49.1400,23.7600,14.9100,27.4300,12.6900
20180629,171.4000,69.4413,181.3800,137.6500,178.4100,164.3500,36.2200,182.6000,76.9300,55.2338,...,44.8700,33.9400,52.4700,31.2400,52.2800,43.2000,23.7600,16.6900,27.0300,12.8900
20180731,176.1000,70.8957,186.1400,135.4500,182.4700,167.0100,37.7300,185.4700,79.3000,56.3561,...,45.6000,34.8600,52.7900,32.2900,51.6900,44.5900,22.1700,15.9900,27.7100,12.2600
20180831,186.6200,75.5952,202.8200,145.6900,195.8200,176.5800,38.7900,200.8400,81.2200,60.5772,...,48.1800,36.6400,58.4500,33.8300,56.3500,47.0000,18.3000,15.0400,27.1400,10.6300
20180928,185.7300,75.3002,202.5100,141.5900,193.9800,175.1800,38.7800,205.0100,79.3600,60.2225,...,47.7600,36.0200,57.9200,33.1800,55.1200,45.0100,18.2600,15.5100,27.1600,10.7500
20181031,169.6900,69.3020,185.3800,126.0200,177.6300,160.3000,35.2000,183.2600,71.5300,55.0015,...,43.1600,32.9200,52.1300,30.9700,50.2700,34.4400,22.1800,19.2000,24.8300,12.4700
20181130,169.5100,67.9968,182.8300,126.3300,174.0700,157.2800,36.3800,185.6800,74.1700,54.0643,...,43.0900,33.8000,52.3200,31.8500,51.2000,34.7700,22.6000,18.3200,24.3900,12.7600
20181231,154.1400,61.9826,166.8500,116.6500,159.7700,144.2400,33.3200,173.4500,67.9700,49.3250,...,39.5400,31.4600,48.4400,28.0500,47.4000,29.7700,27.6900,20.2500,22.0300,14.6400

In [52]:
all_data.to_csv('Technology_Equity _ETF_NAV.csv')